import React,{useEffect,useState}from'react'
import{createRoot}from'react-dom/client'
import{BrowserRouter,Link,Navigate,Route,Routes,useNavigate,useParams}from'react-router-dom'
import{QueryClient,QueryClientProvider,useQuery,useQueryClient}from'@tanstack/react-query'
import{EditorContent,useEditor}from'@tiptap/react'
import StarterKit from'@tiptap/starter-kit'
import Underline from'@tiptap/extension-underline'
import{BarChart3,BookOpen,Check,Copy,FileText,GitBranch,LayoutList,LogOut,MessageCircle,Plus,Settings,Share2,Sparkles,Trash2,UsersRound,X}from'lucide-react'
import{api,auth}from'./api'
import'./styles.css'
import'./overrides.css'
import'./workspace.css'

type User={id:string;email:string;full_name?:string;onboarding_completed?:boolean;is_portfolio_public?:boolean}
type Book={id:string;title:string;description:string;author_name:string;cover_color:string;target_words:number;updated_at:string}
type Chapter={id:string;book_id:string;kind:string;title:string;content:string;position:number}
type Character={id:string;name:string;role?:string;description?:string}
type Post={id:string;title:string;content_snapshot:string;published_at:string;author_name?:string}
type Studio={posts:Post[];post_count:number;words_shared:number}
const clean=(value='')=>value.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()
const words=(value='')=>clean(value).split(/\s+/).filter(Boolean).length
type Theme='light'|'dark'|'paper'
const ThemeContext=React.createContext<{theme:Theme;setTheme:(theme:Theme)=>void}>({theme:'light',setTheme:()=>undefined})
const useTheme=()=>React.useContext(ThemeContext)

function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="modal-wrap" role="dialog" aria-modal="true"><div className="modal rounded-modal"><button className="close" onClick={onClose}><X size={19}/></button><h2>{title}</h2>{children}</div></div>}
function Me(){return useQuery({queryKey:['me'],retry:false,enabled:!!auth.token(),queryFn:()=>api<User>('/auth/me')})}
function Onboarding({user}:{user:User}){const client=useQueryClient(),[name,setName]=useState(user.full_name||'');const save=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;await api('/profile',{method:'PATCH',body:JSON.stringify({full_name:name.trim(),onboarding_completed:true})});client.invalidateQueries({queryKey:['me']})};return <div className="onboarding"><form onSubmit={save}><span className="brand">folio<span>.</span></span><h1>Before you begin</h1><p>What name should appear on your books and posts?</p><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Your writing name"/><button className="primary-btn" type="submit">Continue</button></form></div>}
function Guard({children}:{children:React.ReactNode}){const query=Me();if(query.isLoading&&auth.token())return <div className="center-state">Loading Folio…</div>;if(!query.data)return <Auth/>;return query.data.onboarding_completed?<>{children}</>:<Onboarding user={query.data}/>}
const passage=`At the far end of the room, morning settled into the bookshelves. Dust lifted when the window opened, and every small thing seemed to remember its place: the cup with its pale ring, the chair turned slightly away, the pencil waiting beneath a page. Outside, rain gave the street a softer name. She wrote one sentence, then another, until the quiet around her began to feel less like an absence and more like a door. The story did not arrive all at once. It came by degrees: a voice in the hall, a hand on a railing, the honest weight of a promise kept too long. When she paused, the room was still there, patient as paper, holding the light for her.`
function BookAtmosphere(){const follow=(event:React.PointerEvent<HTMLDivElement>)=>{const box=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty('--spot-x',`${((event.clientX-box.left)/box.width)*100}%`);event.currentTarget.style.setProperty('--spot-y',`${((event.clientY-box.top)/box.height)*100}%`)};return <div className="book-atmosphere" onPointerMove={follow}><p className="book-text-muted">{passage} {passage}</p><p className="book-text-focus" aria-hidden="true">{passage} {passage}</p></div>}
function Auth(){return <div className="auth auth-reading"><BookAtmosphere/><div className="auth-card simple-auth"><span className="brand">folio<span>.</span></span><p>Write your story, one chapter at a time.</p><button className="google" onClick={auth.google}><b>G</b>Continue with Google</button></div></div>}
function Callback(){useEffect(()=>{const token=new URLSearchParams(location.hash.slice(1)).get('access_token');if(token)auth.setToken(token);location.replace('/books')},[]);return <div className="center-state">Finishing sign-in…</div>}

function Shell({children}:{children:React.ReactNode}){const user=Me().data,navigate=useNavigate(),{id}=useParams(),book=id?`/books/${id}`:'/books';return <div className="app"><aside className="sidebar"><Link to="/books" className="brand">folio<span>.</span></Link><nav><Link to="/books"><BookOpen size={17}/>Books</Link><Link to="/feed"><MessageCircle size={17}/>Feed</Link>{id&&<><p className="nav-group">BOOK</p><Link to={`${book}/characters`}><UsersRound size={17}/>Characters</Link><Link to={`${book}/graph`}><GitBranch size={17}/>Graph</Link><Link to={`${book}/timeline`}><LayoutList size={17}/>Timeline</Link></>}<p className="nav-group">CREATE</p><Link to="/studio"><BarChart3 size={17}/>Creator studio</Link></nav><div className="side-bottom"><Link className="settings" to="/settings"><Settings size={17}/>Settings</Link><div className="profile"><b>{(user?.full_name||user?.email||'W').slice(0,2).toUpperCase()}</b><span>{user?.full_name||user?.email}<small>Writer</small></span><button aria-label="Sign out" onClick={()=>{auth.clear();navigate('/books')}}><LogOut size={15}/></button></div></div></aside><main>{children}</main></div>}
function Empty({title,copy,action,label}:{title:string;copy:string;action?:()=>void;label?:string}){return <div className="empty-state"><div><FileText/></div><h2>{title}</h2><p>{copy}</p>{action&&<button className="primary-btn" onClick={action}><Plus size={16}/>{label}</button>}</div>}

function BookForm({onClose}:{onClose:()=>void}){const client=useQueryClient(),navigate=useNavigate(),user=Me().data,[title,setTitle]=useState(''),[description,setDescription]=useState(''),[author,setAuthor]=useState(user?.full_name||''),[colour,setColour]=useState('#556b5c');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!title.trim())return;const book=await api<Book>('/books',{method:'POST',body:JSON.stringify({title:title.trim(),description:description.trim(),author_name:author.trim(),cover_color:colour})});client.invalidateQueries({queryKey:['books']});navigate(`/books/${book.id}`)};return <Modal title="New book" onClose={onClose}><form className="form-stack" onSubmit={submit}><label>Title<input autoFocus required value={title} onChange={e=>setTitle(e.target.value)} placeholder="The title of your book"/></label><label>Author<input required value={author} onChange={e=>setAuthor(e.target.value)} placeholder="Your writing name"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="A short description of this work"/></label><label className="colour-field">Cover colour<input type="color" value={colour} onChange={e=>setColour(e.target.value)}/></label><button className="primary-btn" type="submit">Create book</button></form></Modal>}
function Books(){const books=useQuery({queryKey:['books'],queryFn:()=>api<Book[]>('/books')}),[creating,setCreating]=useState(false);return <Shell><div className="page books"><header><div><p className="eyebrow">YOUR SHELF</p><h1>Books</h1></div><button className="primary-btn" onClick={()=>setCreating(true)}><Plus size={16}/>New book</button></header>{books.data?.length?<div className="book-grid">{books.data.map(book=><Link className="book-card" to={`/books/${book.id}`} key={book.id}><div className="book-cover" style={{backgroundColor:book.cover_color||'#556b5c'}}><span>{book.title.slice(0,1)}</span></div><div><h2>{book.title}</h2><small>{book.author_name||'You'}</small><p>{book.description||'A work in progress.'}</p><time>Edited {new Date(book.updated_at).toLocaleDateString()}</time></div></Link>)}</div>:<Empty title="Your shelf is clear" copy="Create a book, then start with its first chapter." action={()=>setCreating(true)} label="New book"/>}</div>{creating&&<BookForm onClose={()=>setCreating(false)}/>}</Shell>}

function useChapters(){const{id}=useParams();return useQuery({queryKey:['chapters',id],enabled:!!id,queryFn:()=>api<Chapter[]>(`/books/${id}/items`)})}
function ChapterForm({bookId,position,onClose}:{bookId:string;position:number;onClose:()=>void}){const client=useQueryClient(),[title,setTitle]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!title.trim())return;await api(`/books/${bookId}/items`,{method:'POST',body:JSON.stringify({kind:'chapter',title:title.trim(),position})});client.invalidateQueries({queryKey:['chapters',bookId]});onClose()};return <Modal title="New chapter" onClose={onClose}><form className="form-stack" onSubmit={submit}><label>Chapter title<input autoFocus required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Chapter one"/></label><button className="primary-btn" type="submit">Create chapter</button></form></Modal>}
function Editor(){const{id}=useParams(),query=useChapters(),[active,setActive]=useState<string>(),[creating,setCreating]=useState(false),chapters=(query.data||[]).filter(item=>item.kind==='chapter'),chapter=chapters.find(item=>item.id===active)||chapters[0];return <Shell><div className="editor-layout"><aside className="tree"><div className="tree-title"><span>CHAPTERS</span><button onClick={()=>setCreating(true)} aria-label="New chapter"><Plus size={17}/></button></div>{chapters.map(item=><button className={`tree-node ${chapter?.id===item.id?'chosen':''}`} key={item.id} onClick={()=>setActive(item.id)}><FileText size={14}/><b>{item.title}</b></button>)}<div className="tree-add"><button onClick={()=>setCreating(true)}><Plus size={14}/>New chapter</button></div></aside>{chapter?<Writer chapter={chapter}/>:<Empty title="Write your first chapter" copy="Books are built one chapter at a time." action={()=>setCreating(true)} label="New chapter"/>}<aside className="context"><p className="eyebrow">CHAPTER</p><h2>{chapter?.title||'No chapter'}</h2><div><label>WORD COUNT</label><p>{words(chapter?.content).toLocaleString()} words</p></div><div><label>CHARACTERS</label><p>Use Characters to scan your manuscript or add people yourself.</p></div></aside></div>{creating&&id&&<ChapterForm bookId={id} position={chapters.length} onClose={()=>setCreating(false)}/>}</Shell>}
function Writer({chapter}:{chapter:Chapter}){const client=useQueryClient(),[saved,setSaved]=useState(true),[posted,setPosted]=useState(false),editor=useEditor({extensions:[StarterKit,Underline],content:chapter.content,onUpdate:({editor:current})=>{setSaved(false);clearTimeout((window as Window & {folioSave?:number}).folioSave);(window as Window & {folioSave?:number}).folioSave=window.setTimeout(async()=>{await api(`/items/${chapter.id}`,{method:'PATCH',body:JSON.stringify({content:current.getHTML()})});setSaved(true);client.invalidateQueries({queryKey:['chapters',chapter.book_id]})},500)},editorProps:{attributes:{class:'prose'}}});const control=(label:string,run:()=>void)=><button onMouseDown={event=>{event.preventDefault();run()}}>{label}</button>;const finish=async()=>{await api(`/items/${chapter.id}`,{method:'PATCH',body:JSON.stringify({content:editor?.getHTML()||''})});await api(`/chapters/${chapter.id}/finish`,{method:'POST'});setPosted(true)};return <section className="writer"><div className="editor-top"><span>{chapter.title}</span><button className="primary-btn" onClick={finish}>{posted?<><Check size={15}/>Posted</>:'Finish & post'}</button></div><div className="toolbar">{control('B',()=>editor?.chain().focus().toggleBold().run())}{control('I',()=>editor?.chain().focus().toggleItalic().run())}{control('U',()=>editor?.chain().focus().toggleUnderline().run())}{control('•',()=>editor?.chain().focus().toggleBulletList().run())}<span/></div><div className="manuscript"><EditorContent editor={editor}/></div><footer>{words(editor?.getHTML()).toLocaleString()} words <span>{saved?<><Check size={13}/>Saved</>:'Saving…'}</span></footer></section>}

function CharacterForm({bookId,onClose}:{bookId:string;onClose:()=>void}){const client=useQueryClient(),[name,setName]=useState(''),[role,setRole]=useState(''),[description,setDescription]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;await api(`/books/${bookId}/characters`,{method:'POST',body:JSON.stringify({name:name.trim(),role:role.trim(),description:description.trim()})});client.invalidateQueries({queryKey:['characters',bookId]});onClose()};return <Modal title="New character" onClose={onClose}><form className="form-stack" onSubmit={submit}><label>Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label><label>Role<input value={role} onChange={e=>setRole(e.target.value)} placeholder="Protagonist, friend, rival…"/></label><label>Notes<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description and notes"/></label><button className="primary-btn" type="submit">Add character</button></form></Modal>}
function Characters(){const{id}=useParams(),query=useQuery({queryKey:['characters',id],enabled:!!id,queryFn:()=>api<Character[]>(`/books/${id}/characters`)}),client=useQueryClient(),[chosen,setChosen]=useState<string>(),[creating,setCreating]=useState(false),[scanning,setScanning]=useState(false),person=query.data?.find(item=>item.id===chosen)||query.data?.[0];const scan=async()=>{if(!id)return;setScanning(true);await api(`/books/${id}/characters/extract`,{method:'POST'});await client.invalidateQueries({queryKey:['characters',id]});setScanning(false)};return <Shell><div className="page manager"><header><div><p className="eyebrow">CAST</p><h1>Characters</h1></div><div className="header-actions"><button className="secondary-btn" onClick={scan} disabled={scanning}><Sparkles size={16}/>{scanning?'Scanning…':'Scan manuscript'}</button><button className="primary-btn" onClick={()=>setCreating(true)}><Plus size={16}/>New character</button></div></header>{query.data?.length?<div className="characters-layout"><aside>{query.data.map(item=><button key={item.id} className={person?.id===item.id?'active':''} onClick={()=>setChosen(item.id)}><b>{item.name}</b><small>{item.role||'Character'}</small></button>)}</aside>{person&&<CharacterDetail person={person}/>}</div>:<Empty title="No characters yet" copy="Scan the manuscript to find names, or add your first character." action={scan} label="Scan manuscript"/>}</div>{creating&&id&&<CharacterForm bookId={id} onClose={()=>setCreating(false)}/>}</Shell>}
function CharacterDetail({person}:{person:Character}){const client=useQueryClient(),[role,setRole]=useState(person.role||''),[description,setDescription]=useState(person.description||''),[saved,setSaved]=useState(true);useEffect(()=>{setRole(person.role||'');setDescription(person.description||'');setSaved(true)},[person.id]);const save=async()=>{setSaved(false);await api(`/characters/${person.id}`,{method:'PATCH',body:JSON.stringify({role,description})});await client.invalidateQueries({queryKey:['characters']});setSaved(true)};return <section className="character-detail"><h2>{person.name}</h2><label>Role<input value={role} onChange={e=>setRole(e.target.value)} placeholder="Character role"/></label><label>Notes<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description and notes…"/></label><button className="primary-btn" onClick={save}>{saved?'Save changes':'Saving…'}</button></section>}

function Graph(){const query=useChapters(),chapters=(query.data||[]).filter(item=>item.kind==='chapter');return <Shell><div className="page manager"><header><div><p className="eyebrow">STORY</p><h1>Graph</h1></div></header>{chapters.length?<div className="story-graph">{chapters.map((chapter,index)=><React.Fragment key={chapter.id}><article><small>CHAPTER {index+1}</small><b>{chapter.title}</b><span>{words(chapter.content)} words</span></article>{index<chapters.length-1&&<i>→</i>}</React.Fragment>)}</div>:<Empty title="No chapters to map" copy="Add a chapter to start shaping your story."/>}</div></Shell>}
function Timeline(){const query=useChapters(),chapters=(query.data||[]).filter(item=>item.kind==='chapter');return <Shell><div className="page manager"><header><div><p className="eyebrow">STORY</p><h1>Timeline</h1></div></header>{chapters.length?<div className="story-timeline">{chapters.map((chapter,index)=><div key={chapter.id}><i>{index+1}</i><article><small>CHAPTER {index+1}</small><b>{chapter.title}</b><span>{words(chapter.content)} words</span></article></div>)}</div>:<Empty title="No chapters yet" copy="Your story timeline will appear here."/>}</div></Shell>}
function Feed(){const query=useQuery({queryKey:['feed'],queryFn:()=>api<Post[]>('/feed')});return <Shell><div className="feed-page"><header><div><p className="eyebrow">COMMUNITY</p><h1>Feed</h1></div></header>{query.data?.length?<div className="feed-scroll">{query.data.map(post=><article className="feed-post" key={post.id}><div className="feed-meta"><b>{post.author_name||'Folio writer'}</b><span>{new Date(post.published_at).toLocaleDateString()}</span></div><h2>{post.title}</h2><p>{clean(post.content_snapshot).slice(0,330)}{clean(post.content_snapshot).length>330?'…':''}</p></article>)}</div>:<Empty title="The feed is quiet" copy="Finished chapters from every Folio writer appear here."/>}</div></Shell>}
function Studio(){const query=useQuery({queryKey:['studio'],queryFn:()=>api<Studio>('/studio')}),studio=query.data;return <Shell><div className="page studio"><header><div><p className="eyebrow">CREATOR STUDIO</p><h1>Your writing</h1></div></header><div className="metrics"><article><small>POSTS</small><b>{studio?.post_count||0}</b></article><article><small>WORDS SHARED</small><b>{(studio?.words_shared||0).toLocaleString()}</b></article><article><small>LATEST</small><b>{studio?.posts[0]?new Date(studio.posts[0].published_at).toLocaleDateString():'—'}</b></article></div><h2>Published chapters</h2>{studio?.posts.length?<div className="studio-posts">{studio.posts.map(post=><article key={post.id}><b>{post.title}</b><span>{words(post.content_snapshot)} words · {new Date(post.published_at).toLocaleDateString()}</span></article>)}</div>:<Empty title="Nothing published yet" copy="Finish a chapter to see it here."/>}</div></Shell>}
function DeleteAccount({onClose}:{onClose:()=>void}){const navigate=useNavigate(),[confirmation,setConfirmation]=useState(''),[working,setWorking]=useState(false);const remove=async()=>{if(confirmation!=='DELETE')return;setWorking(true);await api('/account',{method:'DELETE'});auth.clear();navigate('/');location.reload()};return <Modal title="Delete account" onClose={onClose}><div className="danger-copy"><p>This permanently deletes your account, books, chapters, characters, and published posts. This cannot be undone.</p><label>Type DELETE to confirm<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} placeholder="DELETE"/></label><button className="danger-btn" disabled={confirmation!=='DELETE'||working} onClick={remove}><Trash2 size={16}/>{working?'Deleting…':'Delete my account'}</button></div></Modal>}
function SettingsPage(){const user=Me().data,client=useQueryClient(),{theme,setTheme}=useTheme(),[deleting,setDeleting]=useState(false),[copied,setCopied]=useState(false);if(!user)return null;const url=`${location.origin}/portfolio/${user.id}`;const toggle=async()=>{await api('/profile',{method:'PATCH',body:JSON.stringify({is_portfolio_public:!user.is_portfolio_public})});client.invalidateQueries({queryKey:['me']})};const copy=async()=>{await navigator.clipboard.writeText(url);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};return <Shell><div className="page settings-page"><header><div><p className="eyebrow">ACCOUNT</p><h1>Settings</h1></div></header><section className="settings-section"><h2>Appearance</h2><p>Choose the reading surface that feels best for your writing.</p><div className="theme-picker">{(['light','paper','dark'] as Theme[]).map(option=><button key={option} className={theme===option?'selected':''} onClick={()=>setTheme(option)}><i className={`theme-swatch ${option}`}/>{option}</button>)}</div></section><section className="settings-section"><h2>Share your work</h2><p>Publish a clean portfolio page of your books, arranged as a small personal shelf.</p><div className="share-panel"><div><b>Your portfolio</b><small>{user.is_portfolio_public?'Visible to anyone with the link':'Private until you turn sharing on'}</small></div><label className="switch"><input type="checkbox" checked={!!user.is_portfolio_public} onChange={toggle}/><span/></label></div>{user.is_portfolio_public&&<div className="share-link"><input readOnly value={url}/><button onClick={copy}><Copy size={16}/>{copied?'Copied':'Copy link'}</button><a href={url} target="_blank" rel="noreferrer"><Share2 size={16}/>Open</a></div>}</section><section className="settings-section"><h2>Legal</h2><p>Using Folio means you agree to our terms and privacy agreement.</p><div className="legal-links"><Link to="/terms">Terms of use</Link><Link to="/privacy">Privacy agreement</Link></div></section><section className="settings-section danger-zone"><h2>Danger zone</h2><p>Deleting your account removes all writing and profile data from Folio.</p><button className="danger-outline" onClick={()=>setDeleting(true)}><Trash2 size={16}/>Delete account</button></section></div>{deleting&&<DeleteAccount onClose={()=>setDeleting(false)}/>}</Shell>}
function Legal({kind}:{kind:'terms'|'privacy'}){const terms=kind==='terms';return <div className="legal-page"><Link className="brand" to="/books">folio<span>.</span></Link><article><p className="eyebrow">FOLIO · {terms?'TERMS OF USE':'PRIVACY AGREEMENT'}</p><h1>{terms?'Terms of use':'Privacy agreement'}</h1>{terms?<><h2>Using Folio</h2><p>Folio is a workspace for writing and sharing your work. You keep ownership of the writing you create. You are responsible for the content you publish and for using Folio lawfully and respectfully.</p><h2>Shared work</h2><p>Finished chapters may appear in the Folio feed and your public portfolio only when you choose to share them. Do not publish material that infringes another person’s rights or violates applicable law.</p><h2>Account changes</h2><p>You can remove your account at any time from Settings. Deleting an account permanently removes its associated Folio data.</p></>:<><h2>What we store</h2><p>Folio stores the account information supplied by your sign-in provider, your profile name, books, chapters, characters, and posts needed to provide the service.</p><h2>How it is used</h2><p>Your writing remains private unless you finish and post a chapter or enable your portfolio. Public portfolio links are visible to anyone who has the link while sharing is enabled.</p><h2>Your choices</h2><p>You can change your portfolio visibility or permanently delete your account in Settings. Deleting the account removes its associated Folio data.</p></>}<p className="legal-updated">Last updated: September 19, 2026</p></article></div>}
type Portfolio={profile:{id:string;full_name?:string};books:Book[]}
function PortfolioPage(){const{id}=useParams(),query=useQuery({queryKey:['portfolio',id],enabled:!!id,queryFn:()=>api<Portfolio>(`/portfolio/${id}`)});if(query.isLoading)return <div className="center-state">Opening portfolio…</div>;if(!query.data)return <div className="center-state">This portfolio is unavailable.</div>;const portfolio=query.data;return <div className="portfolio-page"><header><Link to="/books" className="brand">folio<span>.</span></Link><span>{portfolio.profile.full_name}'s shelf</span></header><main><p className="eyebrow">SELECTED WORK</p><h1>{portfolio.profile.full_name}</h1><div className="portfolio-shelf">{portfolio.books.map(book=><article className="portfolio-book" key={book.id}><div className="portfolio-spine" style={{backgroundColor:book.cover_color||'#556b5c'}}><span>{book.title}</span></div><div><h2>{book.title}</h2><p>{book.description||'A work in progress.'}</p></div></article>)}</div>{!portfolio.books.length&&<p className="portfolio-empty">No books are on this shelf yet.</p>}</main></div>}
function App(){const[theme,setTheme]=useState<Theme>(()=>{const saved=localStorage.getItem('folio_theme');return saved==='dark'||saved==='paper'?saved:'light'});useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('folio_theme',theme)},[theme]);return <ThemeContext.Provider value={{theme,setTheme}}><Routes><Route path="/" element={<Navigate to="/books"/>}/><Route path="/auth/callback" element={<Callback/>}/><Route path="/books" element={<Guard><Books/></Guard>}/><Route path="/books/:id" element={<Guard><Editor/></Guard>}/><Route path="/books/:id/characters" element={<Guard><Characters/></Guard>}/><Route path="/books/:id/graph" element={<Guard><Graph/></Guard>}/><Route path="/books/:id/timeline" element={<Guard><Timeline/></Guard>}/><Route path="/feed" element={<Guard><Feed/></Guard>}/><Route path="/studio" element={<Guard><Studio/></Guard>}/><Route path="/settings" element={<Guard><SettingsPage/></Guard>}/><Route path="/portfolio/:id" element={<PortfolioPage/>}/><Route path="/terms" element={<Legal kind="terms"/>}/><Route path="/privacy" element={<Legal kind="privacy"/>}/></Routes></ThemeContext.Provider>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><BrowserRouter><App/></BrowserRouter></QueryClientProvider>)
